<?php

namespace AppBundle\Repository;

/**
 * ContestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestRepository extends \Doctrine\ORM\EntityRepository
{
	function findCurrentContest($today){
		$qb = $this->createQueryBuilder('c')
    		->where('c.startDate < :today')
    		->andWhere('c.endDate > :today')
    		->setParameter('today', $today);

		return $qb->getQuery()->getResult();
	}
}
