<?php

namespace AppBundle\Repository;

/**
 * ContestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Picture_likeRepository extends \Doctrine\ORM\EntityRepository
{
	function findNbLike($id){
		$qb = $this->createQueryBuilder('c')
			->select('COUNT(c.id)')
    		->where('c.id_picture = :id')
    		->setParameter('id', $id);

		return $qb->getQuery()->getResult();
	}
}
