<?php

namespace AppBundle\Repository;

/**
 * picture_tagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class picture_tagRepository extends \Doctrine\ORM\EntityRepository
{
}
