# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            entity: { class: AppBundle\Entity\User, property: username }
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false

        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
            anonymous: true

            logout:
                path: /logout
                target: /
                
    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
            iterations: 9616
            encode_as_base64: true

    access_control:
        - { path: ^/private/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/private, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
